### ISSUE TITLE
Selecting the correct sender address fails when replying to a message

### ISSUE THREAD

**Issue by dodmi** [dennisverspuij/tb-correctidentity#1]
Thunderbird: 52.8
Correct Identity 1.4.6, 1.4.7
Feature was working correct in version 1.4.5, which isn't compatible to latest Thunderbird versions...

Description:
I have multiple accounts with different identities set up. Therefore, default Thunderbird regularly failed to select the correct sender address. 
I found Correct Identity addon, which has the feature to determine the sender address based on the recipient list of the original message. This worked flawlessly until version 1.4.5 of the addon.
Now, the sender address is the default sender address instead of the sender address based on the recipient list.

**Comment by dennisverspuij** [comment]
Hi Mike, I can't reproduce your problem. What platform and TB version are you using?
Other addons that mangle the addressing interface might be interfering, could you temporarily disable all other addons, restart and verify if it's still not working as expected. If it does, uninstalling, restarting and reinstalling correct identity may help then.

**Comment by Big--Mike** [comment]
At the moment I'm using Thunderbird on Windows 10 1803 x64
I've created a test profile.
There's a message in Local Folders/Archive which is addressed to b@example.com
If you try to reply to that message, a@example.com will be selected as sender address, while it should be b@example.com

[lne5v23i.correctidentity_test.zip](https://github.com/dennisverspuij/tb-correctidentity/files/2040220/lne5v23i.correctidentity_test.zip)

**Comment by Big--Mike** [comment]
I had a look at your very clean code and compared "correctidentity.js" from version 1.4.5 and 1.4.7.
The major change were these lines:
`    if (window.onRecipientsChanged && (window.CorrectIdentity.origOnRecipientsChanged == null)) {
      // Overlay function onRecipientsChanged of chrome://messenger/content/messengercompose/addressingWidgetOverlay.js
      window.CorrectIdentity.origOnRecipientsChanged = window.onRecipientsChanged;
      window.onRecipientsChanged = window.CorrectIdentity.onRecipientsChanged;
    }`

If I comment it out, I get the correct sender address in replies. But recipient based rules won't work anymore :'(

I looked into the functions and ended up in getIdentityForServer, there I uncommented the debug code.
I get this message on opening the example mail:
`CorrectIndentity evaluated hints: b@example.com`
If I click reply, I get these:
`CorrectIndentity evaluated hints: Dennis Verspuij <notifications@github.com>,,`

If I remove the code from above, I get only the first line in the log, so I guess, the problem is, that on the second trigger of getIdentityForServer, Correct Identity forgets the correct sender address based on the recipient and selects the next best fit (in this case the default sender for this account)

**Comment by meiser79** [comment]
I can confirm that commenting out the above mentioned part solves the issue. I didn't check anything regarding regressions as I don't use the recipient based rules.

I'm running TB 52.8.0 under Ubuntu 18.04.

**Comment by dennisverspuij** [comment]
Thanks, I can confirm the routine is triggered twice, I'll have to find out why and eliminate the second call. To be continued...

**Comment by dodmi** [comment]
I finally found a "workaround": The routine is triggered on opening the message window, as `redoIdentity` is triggered upon a recipient change event.
I've replaced the following code in `redoIdentity`
```
if (this.explicitIdentityChosen === null)
{
   // Remember initial identity to revert to when no suggestion is returned
  this.explicitIdentityChosen = false;
  this.initialIdentity = this.accountManager.getIdentity(currentIdentityKey);
  //Components.classes["@mozilla.org/consoleservice;1"]
     //  .getService(Components.interfaces.nsIConsoleService)
     //  .logStringMessage('window: ' + window + ', def: ' + this.initialIdentity);
}
````
by
```
if (this.explicitIdentityChosen === null)
{
   // Remember initial identity to revert to when no suggestion is returned
  this.explicitIdentityChosen = false;
  this.initialIdentity = this.accountManager.getIdentity(currentIdentityKey);
  return;
  //Components.classes["@mozilla.org/consoleservice;1"]
     //  .getService(Components.interfaces.nsIConsoleService)
     //  .logStringMessage('window: ' + window + ', def: ' + this.initialIdentity);
}
```
which simply cancels `redoIdentity` on the first run.
But changing recipients afterwards may change the sender address when according rules exist.
