### ISSUE TITLE
Correct Identity is incompatible with Thunderbird 78.3.1.

### ISSUE THREAD

**Issue by axb-lists** [dennisverspuij/tb-correctidentity#11]
Correct Identity is incompatible with Thunderbird 78.3.1.
(same as many other plugins)

If there's anything we can do to help, pls yell!

**Comment by mateuszwanat** [comment]
@axb-lists Do you find the solution to run this extension on Thunderbird 78?

**Comment by axb-lists** [comment]
> @axb-lists Do you find the solution to run this extension on Thunderbird 78?

I'm afraid not. We'll have to wait till it gets a facelift

**Comment by mviereck** [comment]
"Identity Chooser" seems to do exactly the same.

**Comment by yennor** [comment]
I'm using this version now:
https://github.com/ldreier/tb-correctidentity

it's a fork, and it works in thunderbird >= 78

**Comment by lasselin** [comment]
@yennor Is the xpi available somewhere ?

**Comment by yennor** [comment]
if you use linux you can just "git pull" the repository and execute make_xpi.sh .
Otherwise create a zip file and include:
- scripts
- _locales
- LICENSE
- *.html (all html files)
- *.json (all json files)

scripts and _locales are directories,include them with all subdirectories. rename the zip file to xpi => you should be done.

**Comment by lasselin** [comment]
Hi @yennor ,
Thanks for your reply.
I took a look to build the xpi. but i'm not sure to be the good guy for that. I don't know where to find the make_xpi.sh, ...

Dear @dennisverspuij 
Can you attached the xpi file to the release in Github? So anyone can download it.
Thanks in advance.
Best regards,
