### ISSUE TITLE
TB 60

### ISSUE THREAD

**Issue by dougbreaux** [dennisverspuij/tb-correctidentity#2]
I don't think anything major changed between 59 and 60. Can the supported version be bumped up to 60? That's where the beta currently is.

**Comment by dennisverspuij** [comment]
I haven't tested yet, still using 52.8.0 myself actually. I will upgrade soon and have a look at the [changes](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57#Removed_and_changed_in_mozilla60) introduced in 60. Did you test already? Just download latest xpi and drag it onto the Add-ons Manager interface.

**Comment by dougbreaux** [comment]
I had to download it and edit the RDF file for it to install, but it does seem to be working in 60, best I can tell.

**Comment by leres** [comment]
My system updated to thunderbird 60 so this broke for me; I unzipped, edited install.rdf and rezip'ped and updated thunderbird. It works fine.

The UI changed the way you get to add-on preference; you need to go to Tools -> Add-on Preferences -> Correct Identity. But otherwise I can't find any defects.

**Comment by Big--Mike** [comment]
I've just installed TB60 and tested my configuration. Are you sure, that Correct Identity is working for you?
I can't select any identity in the preferences (the drop downs have no entries)
![image](https://user-images.githubusercontent.com/4572946/43990640-454d0a78-9d5e-11e8-98b1-d3b2eebe4502.png)
If it's working for you, I've a conflict with another addon, which wasn't there in Thunderbird 52...

But for now, I'm back on Thunderbird 52, because I've problems with plenty of my addons...

**Comment by dougbreaux** [comment]
No, it's definitely working here. Both in automatically selecting the correct identity, and in letting me manage that panel you show.

**Comment by dougbreaux** [comment]
(Like you, though, I'm back on 52 because of other add-ons.)

**Comment by dennisverspuij** [comment]
Sorry all for late reply. A couple of week ago I installed TB 60 beta and found that indeed options and triggering of the detection routine seemed to work correctly, but the detection itself failed on some of my tests, it chose default identity while I was expecting an identity found in mail headers. I hope to make time soon to dig into this further, until I'm sure I won't commit version compatibility upgrade. Of course any help much appreciated.

**Comment by Big--Mike** [comment]
Hi @dennisverspuij,
maybe it's the same problem as in my issue overthere: https://github.com/dennisverspuij/tb-correctidentity/issues/1#issuecomment-393280396

The reply address is selected correctly, but afterwards, the default address gets selected, as the address selection is triggered twice.

**Comment by dennisverspuij** [comment]
Yes, exactly that, it seemed to be triggered twice, and the second time the routine gets no information about the message, hence the default identity is selected. Thanks for reminding me about your report. Will look into it asap.

**Comment by Big--Mike** [comment]
Ok, that was all I could contribute. I know nothing about Thunderbird events and how addons work...
It would be very nice, if you could maintain compatibility to Thunderbird 52, as I've still other addons, that really don't work in Thunderbird 60.
But since the problem exists already in Thunderbird 52 and the rest seems to work for you, this shouldn't be a problem...

**Comment by Tapter** [comment]
Any chance this great plugin will ever be updated for TB60? Just finally received it via automatic update and very disappointed that this important plugin won't work anymore....

**Comment by dnfoo** [comment]
+1! Would love to use this great and important plugin again on TB 60.2.

**Comment by lameventanas** [comment]
+1 From me too! I'm using Thunderbird 60.3.3.

**Comment by ygrange** [comment]
Certainly +1ing this issue, even if only to tell the maintainer his work is highly appreciated :) !

**Comment by htgoebel** [comment]
I can confirm this is working for TB 60.*. Preferences are available under Tools -> Add-on Preferences -> Correct Identity as expected. Identities are selected correctly (tested a few entries).

I changed maxVersion in install.rdf within the .xpi-file.

Please go ahead and pulich a new version. Thanks
