### ISSUE TITLE
How to add "Identity Chooser" to Thunderbird 115.7.0

### ISSUE THREAD

**Issue by PilgrimHiker** [dennisverspuij/tb-correctidentity#39]
Hello -

Attempting to download "Correct Identity" AddOn to Thunderbird; keep bumping into dead-ends.  Also attempted to find some way to contact Dennis (via GITHUB as well as a www search), but not possible for a peasant such as I.

Below is the attachment I created in hopes of sending to Dennis; since I could not find a way to do that, I'm posting here in hopes of helpful information.

Apologies for the lack of full clarity of text, but hopefully you can decipher or use whatever skill you have at devination in order to make sense of everything.

Thank you,
Nels

[Dennis.Message.pdf](https://github.com/dennisverspuij/tb-correctidentity/files/14150027/Dennis.Message.pdf)

**Comment by ldreier** [comment]
Hi @PilgrimHiker ,

Correct Identity is a Thunderbird add on, the issue you observed first, is related to trying to install the file into Firefox.

I think [https://support.mozilla.org/en-US/kb/installing-addon-thunderbird](https://support.mozilla.org/en-US/kb/installing-addon-thunderbird) gives a good general guide to install an add on in Thunderbird.

I propose you start at "The ideal case" chapter:
Main point mentioned is, "simply go to the Add-ons Manager tab in **Thunderbird**".

The next chapter on the linked page "A slightly less ideal case (Install from a downloaded XPI file)", could also be used if you "Save" the xpi file locally instead of choosing "Open with Firefox"


Downloading from Github is not required to make it work. This is more for software development.
